name: "Hello World"
description: "Greet someone"
input: 
    name: # Id of the input
        description: "Name of the person to greet"
        default: "Erik"
outputs:
    python:
        description: "Python says"
        value: ${{ steps.python.outputs.output }}
runs:
    using: "composite"
    steps:
        - run: echo Hello ${{ inputs.name }}
          shell: bash
        - id: python
          run: print("Hello From Python")
          shell: python



