
name: CI

on:
    pull_request:
        branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
            version: '320.0.0'
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            export_default_credentials: true

      - name: Install pubsub emulator
        run: |- 
            gcloud components install pubsub-emulator --quiet 

      - name: Run pubsub emulator
        run: |-
            gcloud beta emulators pubsub start --host-port=8085 --quiet &

      - name: Curl pubsub emulator
        run: |-
            curl localhost:8085

      - name: GITHUB_SHA
        run: echo $GITHUB_SHA

      - name: Python step
        run: ./.github/scripts/hello-world.py
        shell: bash

      - uses: ./.github/actions/hello-world
        with:
            name: "$NAME"
        env: 
            NAME: "Klas 2"

      - uses: ./.github/actions/env-file
        with:
            envs: 
                FOO=hello,
                BAR=\"HELLO\, WORLD\",
                FOOBAR=${{ secrets.BAR }},
                EMPTY=,
                BAZ=${{ secrets.FOO }},

      - name: Cat .env file
        run: cat "$HOME/.env"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          #- id: myaction
          #  name: Composite action
          #  uses: actions/hello-world@v1
