# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Mf

on:
  push:
    branches: [ "master" ]
  release:
    types: [prereleased, released]

permissions:
  contents: read

jobs:
  push_master:
    if: ${{ github.event_name == "push" }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push on Master
      run: echo "This should only run on push on master"
    - name: Dump context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT
  prereleased:
    if: ${{ github.event_name == "release" && github.event.action == "prereleased"}}
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3
    - name: Create Pre release
      run: echo "This should only run when a prerelease are created"
    - name: Dump context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT
  released:
    if: ${{ github.event_name == "release" && github.event.action == "released"}}
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3
    - name: Create Pre release
      run: echo "This should only run when a prerelease are created"
    - name: Dump context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT